id: IB74C11A7
legacy_id: P007976
ocr_import_info:
  bdrc_scan_id: W15654
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T09:27:31'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:49:12.742749+00:00'
last_modified: 2022-08-30 22:49:22.074892
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W15654
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW15654
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གནས་ཆེན་གངས་རི་མཚོ་གསུམ་སོགས་ཀྱི་གནས་ཡིག
  author: མཁའ་འགྲོ་ཡེ་ཤེས་མཚོ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.8009902079319084
  ocr_word_median_confidence_index: 0.8600000143051147
quality: null
bases:
  I1KG10453:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10453
      total_pages: 90
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10453.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.8009902079319084
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
