id: IB74C11A7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:28:08+00:00'
last_modified: '2022-06-09T08:12:56.886737+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W15654
  title: གནས་ཆེན་གངས་རི་མཚོ་གསུམ་སོགས་ཀྱི་གནས་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    54A6:
      image_group_id: I1KG10453
      title: Volume 1 of gnas chen gangs ri mtsho gsum sogs kyi gnas yig
      total_pages: 90
      order: 1
      base_file: 54A6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
