id: P007976
initial_creation_type: ocr
source_metadata:
  id: bdr:W15654
  title: གནས་ཆེན་གངས་རི་མཚོ་གསུམ་སོགས་ཀྱི་གནས་ཡིག
  author: ''
  volumes:
    c2591150a62a491396c9d5835f3a3718:
      image_group_id: I1KG10453
      title: ''
      volume_number: 1
      total_pages: 90
ebook_metadata:
  title: གནས་ཆེན་གངས་རི་མཚོ་གསུམ་སོགས་ཀྱི་གནས་ཡིག
  author: ''
  sku: P007976
  cover: cover.jpg
  layers:
  - pagination
