id: P007976
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W15654
  title: གནས་ཆེན་གངས་རི་མཚོ་གསུམ་སོགས་ཀྱི་གནས་ཡིག
  author: ''
  volumes:
    a5df777310b7408d9cbe5393e20e8f67:
      image_group_id: I1KG10453
      title: Volume 1 of gnas chen gangs ri mtsho gsum sogs kyi gnas yig
      volume_number: 1
      total_pages: 90
      base_file: v001.txt
